export const START_ADDING_TEAMS = "START_ADDING_TEAMS"
export const SET_TEAMS = "SET_TEAMS"

export const START_ADDING_POLITICS = "START_ADDING_POLITICS"
export const SET_POLITICS = "SET_POLITICS"

export const START_ADDING_GENERAL = "START_ADDING_GENERAL"
export const SET_GENERAL = "SET_GENERAL"

export const START_ADDING_CAPITALS = "START_ADDING_CAPITALS"
export const SET_CAPITALS = "SET_CAPITALS"